### PR TITLE
added bounds argument to levenberg_marquardt

### PR DESCRIPTION
**Pull request by bjarthur**
clamping the search space drastically improves the fit in my use case, and prevents `SingularException`s being thrown.

while at it i also reformatted the docs to conform to current guidelines.

### CODE REVIEW

**Comment by pkofod** [comment]
@yuyichao or @KristofferC any chance you could take a look at this? I know these are busy times, but the change is relatively small.

I will make one comment myself. The particle swarm PR #218 also adds bounds, and we want to be consistent in the bounds interface, so we have to choose one or the other.

**Comment by matthieugomez** [comment]
Is there any reference for your fix? I would do the following:
- check the bounds before computing `f(n_buffer)` 
- If `n_buffer` is outside the bound, go to the case  `rho < MIN_STEP_QUALITY`)

**Comment by bjarthur** [comment]
i could be mistaken, but i believe algorithm 3.1 in http://www.mathematik.uni-wuerzburg.de/~kanzow/paper/CNSLMP.pdf is equivalent to what i propose.  specifically, their function P<sub>X</sub> is a projection onto the constrained solution space (defined at the end of section 1).  this would be a `clamp` in Julia, no?

**Comment by matthieugomez** [comment]
Cool! And indeed I played with it and your solution does work better. I'm not
a maintainer here but I think it'd be great if you did the following

  * Check that you're within the bound before computing `f(n_buffer)`
  * Write the bounds as l = [1.25, -2.1] u = [Inf, Inf]  rather than [1.25 Inf ; -2.1 Inf], to be consistent with  the optim funcction



On Jul 13 2016, at 9:17 am, Ben Arthur &lt;notifications@github.com&gt; wrote:  

> i could be mistaken, but i believe algorithm 3.1 in [http://www.mathematik
.uni-wuerzburg.de/~kanzow/paper/CNSLMP.pdf](http://www.mathematik.uni-
wuerzburg.de/%7Ekanzow/paper/CNSLMP.pdf&r=cmVwbHkrMDA1ZWY3ZGQ0MmU1N2ExMmU1ZjBmMTcxYjViNGIyNGNjMmFkNGM5NmM5ZmJlN2ZiOTJjZjAwMDAwMDAxMTM5ZTAxNjY5MmExNjljZTA5Mzk4MTkwQHJlcGx5LmdpdGh1Yi5jb20=)
is equivalent to what i propose. specifically, their function PX is a
projection onto the constrained solution space (defined at the end of section
1). this would be a clamp in Julia, no?

>

> —  
> You are receiving this because you commented.  
> Reply to this email directly, [view it on
GitHub](https://github.com/JuliaOpt/Optim.jl/pull/196#issuecomment-232351512&r=cmVwbHkrMDA1ZWY3ZGQ0MmU1N2ExMmU1ZjBmMTcxYjViNGIyNGNjMmFkNGM5NmM5ZmJlN2ZiOTJjZjAwMDAwMDAxMTM5ZTAxNjY5MmExNjljZTA5Mzk4MTkwQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AF733ambsOuQL5nZuq1INWj2XwYZXUtvks5qVOVmgaJpZM4IeOmS&r=cmVwbHkrMDA1ZWY3ZGQ0MmU1N2ExMmU1ZjBmMTcxYjViNGIyNGNjMmFkNGM5NmM5ZmJlN2ZiOTJjZjAwMDAwMDAxMTM5ZTAxNjY5MmExNjljZTA5Mzk4MTkwQHJlcGx5LmdpdGh1Yi5jb20=).

**Comment by pkofod** [comment]
Good to see further discussion here! Thanks for the link, I will have a look. I agree with the recent changes of bounds being two vectors (I think this is quite standard in many other pieces of software, and also in the particle swarm PR).

**Comment by bjarthur** [comment]
box constraints now specified as two vectors, and the projection is done before the calculation of the residual.  seems to work well, though i've had to increase the maximum number of permissible iterations to get it to converge consistently.

**Comment by pkofod** [comment]
Great. 

> seems to work well, though i've had to increase the maximum number of permissible iterations to get it to converge consistently.

I know this is kind of ping-pong, but if you have a reference, and can demonstrate that the "old" version is better, then by no ways am I going to force an inefficient implementation :)

**Comment by bjarthur** [comment]
looking into it further, the problem was just a poor choice of tests.  kraznow et al actually say to project just @matthieugomez suggested, which is how the code stands now.

**Comment by pkofod** [comment]
Okay, then I guess we're pretty close to a merge. I'm not going to ask you to document LM, as you didn't propose to add it from scratch, but thanks for putting the reference in the comments.

I would prefer if `lower` and `upper` where `x_min` and `x_max` for consistency reasons. Also, the "out of bounds x0" cases should be tested. I can make a PR against your branch, or you can include them, that's up to you.

**Comment by bjarthur** [comment]
consistency is good, and i'm happy to make the change, but a quick [search](https://github.com/JuliaOpt/Optim.jl/search?utf8=%E2%9C%93&q=lower) in this package for "lower" shows that it's used quite frequently.

i'll push a test for the out of bounds shortly.

**Comment by pkofod** [comment]
Point taken :) I actually so like lower and upper better now that I look at the different variable names.

**Comment by pkofod** [comment]
I see you added the tests, thank you! I am wondering, is there a reason you didn't use `@test_throws`? Don't bother changing it, I was just wondering. I think the OSX travis builds are having problems today.

**Comment by bjarthur** [comment]
didn't know about `@test_throws`.  much more concise!  change made.  thanks.

**Comment by pkofod** [comment]
As `lower` and `upper` are used in `teh/constrained`, we'll go with that! Thanks a lot, sorry for the long processing time.

**Comment by matthieugomez** [comment]
Thanks @bjarthur and @pkofod

**Pull request merged**
