### PR TITLE
allow optimize() to override default neighbor!() for simulated_annealing

### PR DESCRIPTION
**Pull request by cstook**
Suggest adding neighbor! keyword parameter to optimize() and passing through to simulated_annealing() to allow overriding default_neighbor!

### CODE REVIEW

**Comment by mlubin** [comment]
The infrastructure for passing options is changing with https://github.com/JuliaOpt/Optim.jl/pull/149, so we may want to wait for that to land first.

**Comment by cstook** [comment]
OK, sounds good to me.

I'm learning julia.  Looking forward to reading the new code.

**Comment by pkofod** [comment]
@cstook I think it's almost there, so if you want to know how the changes are going to materialize, you can read the PR now. Great to see a PR which adds useful functionality :+1:

**Comment by Evizero** [comment]
Missed this issue before. #149  takes care of what you ask. See https://github.com/Evizero/Optim.jl/blob/chris/src/simulated_annealing.jl#L40-L43

**Comment by pkofod** [comment]
In that case, I'll close this PR. Thanks for the effort @cstook , but it looks like it's about to be implemented in #149 .

**Pull request closed without merging**
