### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by pkofod** [comment]
This will remove deprecation warnings on master, but will it work on the current release of Julia? I guess not, right?

**Comment by ranjanan** [comment]
You're right actually, I just realized. I think we need to add this to `Compat.jl` and using `@compat`. @tkelman what's the best way forward on this kind of deprecation?

**Comment by tkelman** [comment]
Should put in in Compat but not exported, so you'd have to do `import Compat.view` to get this behavior

**Comment by ranjanan** [comment]
There's a new Compat version that was tagged v0.8.4, Travis seems to fail because it can't find it.

**Comment by tkelman** [comment]
The metadata PR was opened but not yet merged.

**Comment by pkofod** [comment]
I've restarted them

**Comment by ranjanan** [comment]
@pkofod now that the new Compat version has been merged to METADATA, could you restart Travis please?

**Comment by pkofod** [comment]
Restarted! Thought it was merged when I restarted it the last time :)

**Comment by ranjanan** [comment]
Alright, seems that it has passed. Can we merge, @pkofod please?

**Comment by pkofod** [comment]
> Alright, seems that it has passed. Can we merge, @pkofod please?

Don't worry, even if merging takes a few days sometimes :) Your day may be my night! I'm in time zone CEST for example, you might be on the other side of the planet.

**Pull request merged**
