### PR TITLE
stay within bounds

### PR DESCRIPTION
**Pull request by matthieugomez**
See #274

### CODE REVIEW

**Comment by bjarthur** [comment]
great!  thanks for the tests.

the 0.5 CI failed though, but it's probably not your fault as the logs say it just stalled.  but just for completeness, could you please trigger the automatic testing again by squashing your commits and force pushing?  like this:

```
git rebase -i HEAD~2   ##  and then change pick to fixup on the second line
git push --force <github remote> <your branch>
```

while doing so, you might also want to add the number of this PR to the comment in your added test code, for reference.

note that a similar sequence of commands can be used to update a PR instead of submitting a new PR with changes.

**Comment by pkofod** [comment]
You can also just address the comments @bjarthur made, and then commit and push normally. Force pushing always gives me sweaty palms, and we can simply squash and merge from the github interface.

**Comment by anriseth** [comment]
@bjarthur there are other ways to rerun Travis:
- close and reopen the PR
- the package owner can initiate a rerun

**Comment by bjarthur** [comment]
lgtm

**Pull request merged**
