### PR TITLE
Change all tests to testsets and suppress some information by default.

### PR DESCRIPTION
**Pull request by pkofod**
Just something I've been wanting to do for some time. I think we should also move all the identical loops over problems into the `optimize` test set, and let individual files for each solver be there only if we have unit tests for related methods or very specific problems. NewtonTrustRegion is a perfect example with tests for the subproblem solver.

### CODE REVIEW

**Comment by Evizero** [comment]
The 0.4 tests fails could likely be fixed with the following in `runtests.jl` instead of https://github.com/JuliaOpt/Optim.jl/blob/master/test/runtests.jl#L6 

```julia
if VERSION >= v"0.5-"
    using Base.Test
else
    using BaseTestNext
    const Test = BaseTestNext
end
```

and a `BaseTestNext` in `REQUIRE`

**Comment by Evizero** [comment]
unsure about the win32 fail.

**Comment by pkofod** [comment]
> unsure about the win32 fail.

That is some weird `Fminbox` failure that I have yet to figure out. Somewhere the objective (including the barrier) returns `NaN`, and it is while calculating the barrier contribution I believe, as it never actually reaches the `fg!` call. I don't have a 32bit install, so it's kind of slow to debug (through a PR and watching the output of AppVeyor).

**Comment by pkofod** [comment]
> The 0.4 tests fails could likely be fixed with the following in runtests.jl instead of https://github.com/JuliaOpt/Optim.jl/blob/master/test/runtests.jl#L6
> 
> if VERSION >= v"0.5-"
>     using Base.Test
> else
>     using BaseTestNext
>     const Test = BaseTestNext
> end
> 
> and a BaseTestNext in test/REQUIRE

I'll try it out tomorrow. Thanks. It's actually impressive how little we have to do to support v0.4 through v0.6. Julia sure is stabilizing! (at least the parts we use).

**Comment by pkofod** [comment]
Great. v0.4 now passes. It's running again due to a merge conflict I had to handle, and I also added some test sets I had missed.

**Comment by tkelman** [comment]
You should use a more specific VERSION cutoff than that. Base.test did not support testsets for all 0.5 prerelease versions.

**Comment by pkofod** [comment]
@tkelman okay. Is there an easy way to get the build number, or should I just build the specific commit and see?

**Comment by tkelman** [comment]
check other packages, they mostly have it right. or run contrib/commit-name.sh

**Pull request merged**
