### PR TITLE
Documentation for Preconditioning

### PR DESCRIPTION
**Pull request by cortner**

### CODE REVIEW

**Comment by pkofod** [comment]
I will process this asap (don't have time right now).

**Comment by pkofod** [comment]
Could I convince you to fill in the example from the test you provided ? Other than that it looks good.

**Comment by cortner** [comment]
It is a little bit long maybe?

```
W(r) = (1+r.^2).^2
W1(r) = 4 * (1+r.^2) .* r
h(U) = length(U)-1
plap(U) = h(U) * sum( W(diff(U)) ) - sum(U) / h(U)
plap1(U) = h(U) * ([0.0; W1(diff(U))] - [W1(diff(U)); 0.0]) - ones(U) / h(U)
plap_objective(X::Vector) = plap([0;X;0])
plap_objective_gradient!(X::Vector, G) = copy!(G, plap1([0;X;0])[2:end-1])
lap_precond(X::Vector) =
    spdiagm( ( (-1) * ones(length(X)-1),
                 2  * ones(length(X)),
               (-1) * ones(length(X)-1) ),
             (-1,0,1), length(X), length(X) ) * (length(X)+1)
```

**Comment by cortner** [comment]
I guess I can try to cut it down a bit.

**Comment by pkofod** [comment]
Just something that a user can copy+paste, if that makes sense?

**Comment by cortner** [comment]
I can't make an edit since I don't have push access, and there is branch information, so I can't pull it either. (I edited the README directly on github.)

But if you want to add it yourself, here are the lines compressed to a bare minimum. I'll also push a new `tests/precon.jl` with this change.
```
using Optim, ForwardDiff
using Optim, ForwardDiff
plap(U; n=length(U)) = (n-1) * sum( (0.1 + diff(U).^2).^2 ) - sum(U) / (n-1)
plap1 = ForwardDiff.gradient(plap)
precond(n) = spdiagm( ( -ones(n-1), 2*ones(n), -ones(n-1) ), (-1,0,1), n, n) * (n+1)
df = DifferentiableFunction( X->plap([0;X;0]),
                             (X, G)->copy!(G, (plap1([0;X;0]))[2:end-1]) )
result = Optim.optimize(df, zeros(100), method=ConjugateGradient(P = nothing) )
result = Optim.optimize(df, zeros(100), method=ConjugateGradient(P = precond(100)) )
```

**Comment by pkofod** [comment]
> I can't make an edit since I don't have push access, and there is branch information, so I can't pull it either. (I edited the README directly on github.)

This is because you have deleted your fork of `Optim.jl ` on your account.

**Comment by cortner** [comment]
oh - I didn't realise that was also used for the doc pull request.

**Comment by pkofod** [comment]
No worries. At least Github retains a copy of the branch for the sake of the open PR, so no information was lost. The example is great.

**Comment by cortner** [comment]
glad you like it.

**Pull request merged**
