### PR TITLE
BFGS and Newton: reset initial linesearch step to one

### PR DESCRIPTION
**Pull request by anriseth**
Resetting the initial step for the linesearch to one after each iteration in Newton and BFGS improves convergence: 
Newton CUTEst tests with maxvar = 5:
f_err_cutest
BFGS CUTEst tests with maxvar = 5:
f_err_bfgs_cutest

BT3 is backtracking with cubic interpolation, added in anriseth/LineSearches.jl#20. The behaviour for quadratic bactracking is similar.
LBFGS already has a variant of this implemented, so I haven't added it there.
Ref #91

### CODE REVIEW

**Comment by pkofod** [comment]
Just out of curiosity, did you choose 5 because of optimtests.jl? I chose that to quickly debug the code when migrating. I love that we're beginning to have a tool to say *something* about the quality of changes. I would love to see it for some large(r) scale problems as well. But it looks very promising!

**Comment by anriseth** [comment]
Yep, I just copied your benchmark code from OptimTests.jl.
Here's a run with maxvar = 20 (my laptop is slow, so I can't go much higher):
f_err_cutest

**Comment by pkofod** [comment]
It almost looks good to me, but the entry in the docs for the constructors have to be updated.

**Comment by pkofod** [comment]
@anriseth pinging in case you missed it. I know you might be busy, but :)

**Comment by anriseth** [comment]
I'll be on it sometime next week, when I'm back from holiday ;)

**Comment by pkofod** [comment]
Great, Sorry if I bothered you on your vacation!

**Comment by anriseth** [comment]
Updated the docs now. Are the changes clear enough?

**Comment by pkofod** [comment]
Great, thanks for doing this.

**Pull request merged**
