### PR TITLE
Fix problem dimensions inside the method

### PR DESCRIPTION
**Pull request by alyst**
Modify the methods to respect the problem dimensions, so that `df.f()`, `df.fg!()`, `df.g!()` are called with the correct `x`, `grad` and `hessian` argument types. E.g. currently `Fminbox` fails when I submit the problem with `x` being a matrix.

### CODE REVIEW

**Comment by pkofod** [comment]
Wonderful! I've been meaning to get this working again - also ref #198, but havn't had the time. This is really appreciated.

I've restarted travis.

Two things before I merge.

1) Could you add an entry to the documentation about this? Just a simple section where you show that either input will return the same thing. The relevant file is https://github.com/JuliaOpt/Optim.jl/blob/ccc51d73621988265f77b5e42cf2393f444491ec/docs/src/user/minimization.md and you can add it just before box minimization.

2) We need some test to make sure this doesn't regress. I guess it would suffice to loop over the methods optimizing some simple problem (you can take one from the unconstrained problems module) solving it with the vector- and matrix-input and checking the results are identical. This will ensure a) that everything can run and b) it returns the (exact [besides randomized methods]) same thing.

Oh, and a tiny thing. Can you add a line to NEWS.md saying that x is no longer restricted to be a vector ref #198 .

Once again, thanks.

**Comment by alyst** [comment]
@pkofod I'm a little bit busy these days, but your suggestions make total sense, I will update the PR in a week or two.

**Comment by pkofod** [comment]
> @pkofod I'm a little bit busy these days, but your suggestions make total sense, I will update the PR in a week or two.

No worry, this is all voluntary. When you update this PR, I'll make sure to review it quickly.

**Comment by pkofod** [comment]
I'll open a new PR in a bit, with the proposed changes. I'll keep your changes under your name, so you'll still get credit in the git history. Thanks for doing this.

**Comment by pkofod** [comment]
thank you for the effort, but this is now superseded by #337

**Comment by alyst** [comment]
@pkofod for the reference, #345 implemented (I don't know whether independently or not) parts of #312 that addresses using proper dimensions, but not all. E.g. the Hessian in Newton method. Also I have to note that while #345 was merged, it didn't introduce the test cases either.

**Comment by pkofod** [comment]
Sure, but that PR was to remove warnings, it didn't claim to fix the bug you brought up. I just wanted the warnings on Travis to go away.

**Comment by alyst** [comment]
@pkofod next time I would be more modest in the PR description ;)

**Comment by pkofod** [comment]
Earlier your could do this. Then there were changes, and a bug was introduced. Then you opened this pr with a fix, but no tests. If I had merged and closed the issue, then the bug could silently creep in again. Providing tests is not really a horrible thing to ask for. I really do appreciate all contributions, but merging stuff without proper tests is what made it possible to introduce this  bug in the first place. In the mean time the old style constructors were removed on master, and I changed the lines that blocked Travis. I did not have this problem in mind at all when doing that.

**Comment by pkofod** [comment]
Looking through my notes: I didn't add the hessian due to the backslash operator/factorization, which was part of the background for comment #5

**Pull request closed without merging**
