### PR TITLE
fix wrong length in buffers in LM

### PR DESCRIPTION
**Pull request by KristofferC**
also adds a tab -> space. For no whitespace diff: https://github.com/KristofferC/Optim.jl/commit/41a8eb3906da81af693203815cb0d60c644ef5bf?w=1

Confirmed that LsqFit passes after this. We should have a in repo test for this as well but I am a bit short of time now.

### CODE REVIEW

**Comment by KristofferC** [comment]
cc @yuyichao can you confirm with `LsqFit`?

**Comment by yuyichao** [comment]
`LsqFit` test passes but the change looks wrong?

Sth like
```
diff --git a/src/levenberg_marquardt.jl b/src/levenberg_marquardt.jl
index 5afe1e6..00cad6a 100644
--- a/src/levenberg_marquardt.jl
+++ b/src/levenberg_marquardt.jl
@@ -97,9 +97,9 @@ function levenberg_marquardt{T}(f::Function, g::Function, x0::AbstractVector{T};
         end
         # try the step and compute its quality
         @simd for i in 1:n
-            @inbounds x_buff[i] = x[i] + delta_x[i]
+            @inbounds Jf_buff[i] = x[i] + delta_x[i]
         end
-        trial_f = f(x_buff)
+        trial_f = f(Jf_buff)
         f_calls += 1
         trial_residual = sumabs2(trial_f)
         # step quality = residual change / predicted residual change
```
? Or use a new buffer to avoid aliasing.

**Comment by KristofferC** [comment]
Yeah, what I had only worked because M > N or vice versa.

**Comment by yuyichao** [comment]
Well it is not giving the right dimension to `f` either.

**Comment by KristofferC** [comment]
Bump, should be good now but good to have more eyes. @yuyichao

**Comment by yuyichao** [comment]
The change LGTM. Probably need a test.

**Comment by pkofod** [comment]
Took the liberty of making a PR to your ( @KristofferC ) branch with a test. Basically, it's the test from `LsqFit.jl`, but stripped to only use `Optim.jl` functions. Fails on maste, but works with this pr.

**Comment by pkofod** [comment]
Currently has conflicts, but I will merge when they're resolved.

**Comment by KristofferC** [comment]
Ok will do it now.

**Comment by pkofod** [comment]
Thanks. I think they're partially because of the changed API for getting the results, but it might be other stuff as well.

**Comment by KristofferC** [comment]
I might have messed up and lost your commit authorship in the rebase. Is that ok, else I can try some other way.

**Comment by KristofferC** [comment]
Think I fixed it.

**Comment by pkofod** [comment]
The authorship doesn't matter, I was just trying to be helpful :)

If the tests pass, I'll merge. Great to get this :bug: fixed.

**Comment by KristofferC** [comment]
:+1:

**Pull request merged**
